-- Curated shortcuts for the mastery page. IDs are stable because local progress
-- is stored against them in stdpath('state').
--
-- Future AI integration (intentionally deferred): with explicit opt-in, an
-- assistant could use current filetype, active tools, tutor mastery, and local
-- shortcut usage to explain context, recommend the next shortcut, and rotate
-- the practice queue. Keep the current system local and deterministic until
-- that privacy and product scope are designed deliberately.
return {
    active = {
        'yazi-normal',
        'yazi-right',
        'yazi-bottom',
        'split-focus',
        'divider-horizontal',
        'divider-vertical',
        'split-equalize',
        'split-close',
    },
    sections = {
        {
            id = 'editing',
            title = 'CORE EDITING & MOTIONS',
            description = 'Small commands that compound into fluent editing.',
            items = {
                { id = 'save-file', action = 'Save current file', keys = 'SPACE W', vim = '<leader>w' },
                { id = 'undo-redo', action = 'Undo / redo', keys = 'U / CTRL R', vim = 'u / <C-r>' },
                { id = 'open-line', action = 'Insert line below / above', keys = 'O / SHIFT O', vim = 'o / O' },
                { id = 'word-motion', action = 'Next / previous / word end', keys = 'W / B / E', vim = 'w / b / e' },
                { id = 'line-edges', action = 'Start / end of line', keys = '0 / $', vim = '0 / $' },
                { id = 'file-edges', action = 'Top / bottom of file', keys = 'G G / SHIFT G', vim = 'gg / G' },
                { id = 'copy-paste-line', action = 'Copy / paste line', keys = 'Y Y / P', vim = 'yy / p' },
                { id = 'delete-line', action = 'Delete line', keys = 'D D', vim = 'dd', detail = 'Deletes into a register, so p can restore it.' },
                { id = 'visual-modes', action = 'Character / line / block select', keys = 'V / SHIFT V / CTRL V', vim = 'v / V / <C-v>' },
                { id = 'search-word', action = 'Search word under cursor', keys = '*', vim = '*', detail = 'Use n / N to move through matches.' },
                { id = 'search-repeat', action = 'Next / previous match', keys = 'N / SHIFT N', vim = 'n / N' },
                { id = 'comment-line', action = 'Comment current line', keys = 'G C C', vim = 'gcc' },
                { id = 'comment-selection', action = 'Comment selection', keys = 'G C', vim = 'gc' },
                { id = 'format-file', action = 'Format buffer / selection', keys = 'SPACE F', vim = '<leader>f' },
                { id = 'surround-add', action = 'Add surrounding pair', keys = 'S A', vim = 'sa' },
                { id = 'surround-delete', action = 'Delete surrounding pair', keys = 'S D', vim = 'sd' },
                { id = 'surround-replace', action = 'Replace surrounding pair', keys = 'S R', vim = 'sr' },
                { id = 'key-bank', action = 'Open Shortcut Atlas', keys = 'SPACE K', vim = '<leader>k' },
            },
        },
        {
            id = 'workspace',
            title = 'SPLIT WORKSPACE',
            description = 'Use the 4K canvas: open, place, focus, resize, and close panels.',
            items = {
                {
                    id = 'split-focus',
                    action = 'Focus split by direction',
                    keys = 'CTRL H / J / K / L',
                    vim = '<C-h/j/k/l>',
                    detail = 'Move focus left, down, up, or right.',
                },
                {
                    id = 'yazi-right',
                    action = 'Open file on right',
                    keys = 'SPACE _',
                    vim = '<leader>_',
                    detail = 'Choose any file in Yazi and place it in a fixed right split.',
                },
                {
                    id = 'yazi-bottom',
                    action = 'Open file below',
                    keys = 'SPACE |',
                    vim = '<leader>|',
                    detail = 'Choose any file in Yazi and place it in a fixed bottom split.',
                },
                {
                    id = 'buffer-save-close',
                    action = 'Save + close focused file',
                    keys = 'SPACE Q Q',
                    vim = '<leader>qq',
                    detail = 'Save and close only the focused buffer/split; Neovim stays open.',
                },
                {
                    id = 'split-close',
                    action = 'Close focused split',
                    keys = 'SPACE Q C',
                    vim = '<leader>qc',
                    detail = 'Close only the current window; modified files remain protected.',
                },
                {
                    id = 'divider-horizontal',
                    action = 'Move divider left / right',
                    keys = 'ALT H / L',
                    vim = '<M-h/l>',
                    detail = 'Direction stays screen-relative from either side of the divider.',
                },
                {
                    id = 'divider-vertical',
                    action = 'Move divider down / up',
                    keys = 'ALT J / K',
                    vim = '<M-j/k>',
                    detail = 'Direction stays screen-relative from above or below.',
                },
                {
                    id = 'split-equalize',
                    action = 'Equalize split sizes',
                    keys = 'SPACE P =',
                    vim = '<leader>p=',
                    detail = 'Give every visible split an even share.',
                },
                {
                    id = 'yazi-normal',
                    action = 'Browse with Yazi',
                    keys = 'SPACE -',
                    vim = '<leader>-',
                    detail = 'Open at the current file; Enter replaces the current buffer.',
                },
                {
                    id = 'buffer-prev-next',
                    action = 'Previous / next file tab',
                    keys = 'ALT , / .',
                    vim = '<M-,/.>',
                    detail = 'Cycle bufferline tabs without changing split focus.',
                },
                {
                    id = 'buffer-number',
                    action = 'Jump to file tab 1–9',
                    keys = 'ALT 1–9',
                    vim = '<M-1..9>',
                    detail = 'Open a visible file tab by its ordinal number.',
                },
                {
                    id = 'buffer-new-close',
                    action = 'New / close file tab',
                    keys = 'ALT N / W',
                    vim = '<M-n/w>',
                    detail = 'Create an empty buffer or close the current unmodified tab.',
                },
                { id = 'buffer-move', action = 'Move file tab left / right', keys = 'ALT < / >', vim = '<M-</>>', detail = 'Reorder the current file tab.' },
            },
        },
        {
            id = 'search',
            title = 'FIND & NAVIGATE',
            description = 'Reach files, symbols, diagnostics, and help without browsing manually.',
            items = {
                { id = 'find-files', action = 'Find project files', keys = 'SPACE S F', vim = '<leader>sf' },
                { id = 'live-grep', action = 'Search text across project', keys = 'SPACE S G', vim = '<leader>sg' },
                { id = 'grep-word', action = 'Search current word', keys = 'SPACE S W', vim = '<leader>sw' },
                { id = 'search-open', action = 'Search open files', keys = 'SPACE S /', vim = '<leader>s/' },
                { id = 'search-buffer', action = 'Fuzzy search current buffer', keys = 'SPACE /', vim = '<leader>/' },
                { id = 'recent-files', action = 'Recent files', keys = 'SPACE S .', vim = '<leader>s.' },
                { id = 'resume-search', action = 'Resume last search', keys = 'SPACE S R', vim = '<leader>sr' },
                { id = 'search-diagnostics', action = 'Search diagnostics', keys = 'SPACE S D', vim = '<leader>sd' },
                { id = 'search-help', action = 'Search Neovim help', keys = 'SPACE S H', vim = '<leader>sh' },
                { id = 'search-keymaps', action = 'Search every keymap', keys = 'SPACE S K', vim = '<leader>sk' },
            },
        },
        {
            id = 'build',
            title = 'DROP REACTOR · BUILD & RUN',
            description = 'Compile, run, measure, and inspect C/raylib work.',
            items = {
                {
                    id = 'c-run-debug',
                    action = 'Save + run debug',
                    keys = 'SPACE M R',
                    vim = '<leader>mr',
                    detail = 'Build and run; routine raylib startup logs fold away.',
                },
                {
                    id = 'c-build-debug',
                    action = 'Build debug',
                    keys = 'SPACE M B',
                    vim = '<leader>mb',
                    detail = 'Debug symbols plus address/undefined-behavior sanitizers.',
                },
                {
                    id = 'c-build-release',
                    action = 'Build release',
                    keys = 'SPACE M SHIFT R',
                    vim = '<leader>mR',
                    detail = 'Optimized and stripped with statically linked raylib.',
                },
                {
                    id = 'c-size',
                    action = 'Release size report',
                    keys = 'SPACE M Z',
                    vim = '<leader>mz',
                    detail = 'File bytes, static sections, and self-contained dependency check.',
                },
                { id = 'c-clean', action = 'Clean game build', keys = 'SPACE M K', vim = '<leader>mk' },
                { id = 'c-flags', action = 'Generate clangd flags', keys = 'SPACE M G', vim = '<leader>mg' },
                { id = 'c-stop', action = 'Stop running C task', keys = 'SPACE M S', vim = '<leader>ms' },
                { id = 'c-output', action = 'Toggle task output dock', keys = 'SPACE M D', vim = '<leader>md' },
                {
                    id = 'c-tutor-mode',
                    action = 'Cycle C tutor mode',
                    keys = 'SPACE M T',
                    vim = '<leader>mt',
                    detail = 'Ask mode is explicit; coach mode observes only stable saved C context.',
                },
                {
                    id = 'c-tutor-explain',
                    action = 'Explain root diagnostic',
                    keys = 'SPACE M E',
                    vim = '<leader>me',
                    detail = 'Names the C rule and gives one learning-first hint without editing.',
                },
                { id = 'c-tutor-more', action = 'Deeper tutor hint', keys = 'SPACE M M', vim = '<leader>mm' },
                {
                    id = 'c-tutor-reroll',
                    action = 'Reroll tutor response',
                    keys = 'SPACE M U',
                    vim = '<leader>mu',
                    detail = 'Bypasses cached content; a successful fresh answer replaces the decoration and cache entry.',
                },
                { id = 'c-tutor-dismiss', action = 'Dismiss tutor response', keys = 'SPACE M X', vim = '<leader>mx' },
            },
        },
        {
            id = 'code',
            title = 'CODE INTELLIGENCE',
            description = 'Ask clangd about the program instead of searching text blindly.',
            items = {
                { id = 'lsp-hover', action = 'Hover documentation', keys = 'SHIFT K', vim = 'K' },
                { id = 'lsp-rename', action = 'Rename symbol safely', keys = 'G R N', vim = 'grn' },
                { id = 'lsp-action', action = 'Code actions', keys = 'G R A', vim = 'gra' },
                { id = 'lsp-definition', action = 'Go to definition', keys = 'G R D', vim = 'grd' },
                { id = 'lsp-references', action = 'Find references', keys = 'G R R', vim = 'grr' },
                { id = 'lsp-implementation', action = 'Find implementation', keys = 'G R I', vim = 'gri' },
                { id = 'lsp-type', action = 'Go to type definition', keys = 'G R T', vim = 'grt' },
                { id = 'lsp-symbols', action = 'Document symbols', keys = 'G SHIFT O', vim = 'gO' },
                { id = 'diag-next', action = 'Next diagnostic', keys = '] D', vim = ']d' },
                { id = 'diag-prev', action = 'Previous diagnostic', keys = '[ D', vim = '[d' },
            },
        },
        {
            id = 'debugger',
            title = 'DEBUGGER',
            description = 'Control execution, inspect state, and test hypotheses.',
            items = {
                { id = 'debug-breakpoint', action = 'Toggle breakpoint', keys = 'LOWER + V', vim = 'F9' },
                { id = 'debug-start', action = 'Start / continue', keys = 'LOWER + G', vim = 'F5' },
                { id = 'debug-terminate', action = 'Terminate debugger', keys = 'LOWER + C', vim = 'F8' },
                { id = 'debug-over', action = 'Step over', keys = 'LOWER + B', vim = 'F10' },
                { id = 'debug-into', action = 'Step into', keys = 'F11', vim = 'F11' },
                { id = 'debug-out', action = 'Step out', keys = 'SHIFT F11', vim = '<S-F11>' },
                {
                    id = 'debug-eval',
                    action = 'Evaluate under cursor',
                    keys = 'SPACE D E',
                    vim = '<leader>de',
                    detail = 'Ask codelldb to calculate an expression in the paused frame.',
                },
                { id = 'debug-conditional', action = 'Conditional breakpoint', keys = 'SPACE D SHIFT B', vim = '<leader>dB' },
                { id = 'debug-logpoint', action = 'Log point', keys = 'SPACE D L', vim = '<leader>dl' },
                { id = 'debug-cursor', action = 'Run to cursor', keys = 'SPACE D G', vim = '<leader>dg' },
                { id = 'debug-ui', action = 'Toggle debugger UI', keys = 'SPACE D U', vim = '<leader>du' },
            },
        },
        {
            id = 'git',
            title = 'GIT & REVIEW',
            description = 'Inspect and manage changes without leaving the editor.',
            items = {
                { id = 'git-next', action = 'Next / previous change', keys = '] C / [ C', vim = ']c / [c' },
                { id = 'git-preview', action = 'Preview hunk', keys = 'SPACE H P', vim = '<leader>hp' },
                { id = 'git-stage', action = 'Stage hunk', keys = 'SPACE H S', vim = '<leader>hs' },
                { id = 'git-reset', action = 'Reset hunk', keys = 'SPACE H R', vim = '<leader>hr' },
                { id = 'git-blame', action = 'Blame current line', keys = 'SPACE H B', vim = '<leader>hb' },
                { id = 'git-diff', action = 'Diff against index', keys = 'SPACE H D', vim = '<leader>hd' },
                { id = 'quickfix-open', action = 'Open quickfix', keys = 'SPACE Q F', vim = '<leader>qf' },
                { id = 'quickfix-next', action = 'Next / previous quickfix', keys = 'SPACE Q N / Q P', vim = '<leader>qn/qp' },
            },
        },
    },
}
