local function gh(repo) return 'https://github.com/' .. repo end

-- The native lockfile pins exact revisions. These specs define which upstream
-- line each plugin follows when vim.pack.update() is explicitly reviewed.
return {
    gh 'numToStr/Comment.nvim',
    { src = gh 'L3MON4D3/LuaSnip', version = vim.version.range '2.*' },
    { src = gh 'saghen/blink.cmp', version = vim.version.range '1.*' },
    { src = gh 'akinsho/bufferline.nvim', version = vim.version.range '*' },
    gh 'rhart92/codex.nvim',
    gh 'stevearc/conform.nvim',
    gh 'sainnhe/everforest',
    gh 'j-hui/fidget.nvim',
    gh 'lewis6991/gitsigns.nvim',
    gh 'NMAC427/guess-indent.nvim',
    gh 'lukas-reineke/indent-blankline.nvim',
    gh 'folke/lazydev.nvim',
    gh 'nvim-lualine/lualine.nvim',
    gh 'mason-org/mason-lspconfig.nvim',
    gh 'jay-babu/mason-nvim-dap.nvim',
    gh 'WhoIsSethDaniel/mason-tool-installer.nvim',
    gh 'mason-org/mason.nvim',
    gh 'echasnovski/mini.nvim',
    gh 'IogaMaster/neocord',
    gh 'windwp/nvim-autopairs',
    gh 'NvChad/nvim-colorizer.lua',
    gh 'mfussenegger/nvim-dap',
    gh 'leoluz/nvim-dap-go',
    gh 'rcarriga/nvim-dap-ui',
    gh 'mfussenegger/nvim-lint',
    { src = gh 'neovim/nvim-lspconfig', version = vim.version.range '2.*' },
    gh 'nvim-neotest/nvim-nio',
    { src = gh 'nvim-treesitter/nvim-treesitter', version = 'main' },
    gh 'nvim-treesitter/nvim-treesitter-context',
    gh 'nvim-tree/nvim-web-devicons',
    gh 'stevearc/overseer.nvim',
    gh 'nvim-lua/plenary.nvim',
    gh 'MeanderingProgrammer/render-markdown.nvim',
    gh 'seblyng/roslyn.nvim',
    gh 'b0o/schemastore.nvim',
    { src = gh 'luckasRanarison/tailwind-tools.nvim', name = 'tailwind-tools' },
    gh 'nvim-telescope/telescope-fzf-native.nvim',
    gh 'nvim-telescope/telescope-ui-select.nvim',
    gh 'nvim-telescope/telescope.nvim',
    gh 'rachartier/tiny-inline-diagnostic.nvim',
    gh 'folke/todo-comments.nvim',
    gh 'folke/trouble.nvim',
    gh 'pmizio/typescript-tools.nvim',
    gh 'folke/which-key.nvim',
    gh 'mikavilpas/yazi.nvim',
}
